M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu23.04.1} date Tue Oct 17 16:33:49 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-17T16:33:49+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu23.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X70.0Y-50.0
X70.0Y-70.0
X90.0Y-50.0
T0
M30
