M48
; DRILL file {KiCad 7.0.5.1-1-g8f565ef7f0-dirty-deb11} date Sat Jun  3 20:03:32 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-03T20:03:32+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5.1-1-g8f565ef7f0-dirty-deb11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X70.0Y-50.0
X70.0Y-70.0
X90.0Y-50.0
T0
M30
